name: Deploy React App

on:
  push:
    branches:
      - develop
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=N975gGRwZXSrpGLGMTfJr1B4
      - name: Build Project Artifacts
        run: vercel build --token=N975gGRwZXSrpGLGMTfJr1B4
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=N975gGRwZXSrpGLGMTfJr1B4
